# railway.toml

[build]
command = "npm run build"
# Zbuduj aplikację przed uruchomieniem serwera

[[services]]
internal_port = 3000
# Wewnętrzny port, na którym działa serwer Express.js

[deploy]
public = "./dist"
# Katalog publiczny, zawierający wygenerowane pliki aplikacji

[[routes]]
handle = "filesystem"
base = "/"

[[services.routes]]
handle = "serve"
src = "./dist"
# Serwuj pliki z katalogu "./dist"

[[services.routes]]
handle = "static"
root = "./dist"
# Obsługuj żądania statyczne z katalogu "./dist"

[[statics]]
path = "/static"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/favicon.ico"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/logo.svg"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/manifest.json"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/robots.txt"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/sitemaps/sitemap.xml"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/sw.js"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/workbox-*.js"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/precache-manifest-*.js"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/precache-manifest-*.css"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/static/js/*.chunk.js"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/static/css/*.chunk.css"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/static/media/*"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/assets/*"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/userMain/*"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/board/*"
headers = { "Cache-Control" = "max-age=86400" }

[[statics]]
path = "/*"
headers = { "Cache-Control" = "max-age=0" }
destination = "/index.html"
